#!/bin/dash

cd $(dirname $0)
#./launcher

if [ $(pgrep -cx "panel") -gt 1 ] ; then
    printf "%s\n" "The panel is already running." >&2
    kill $(pgrep -x "panel_bar")
    #exit 1
fi

trap 'trap - TERM; kill 0; exit' INT TERM QUIT EXIT

flavor=${1:-bar}

bspc control --subscribe > "$PANEL_FIFO" &
#xtitle -sf 'T%s' > "$PANEL_FIFO" &
#clock -sf 'S%a %H:%M' > "$PANEL_FIFO" &
echo "T" >  "$PANEL_FIFO" &
conky -q -c ./panel_conky > "$PANEL_FIFO" &

case "$flavor" in
    bar)
        cat "$PANEL_FIFO" | ./panel_bar | bar -B '#FF181512' -F '#FFBEA492' -f "-misc-stlarch-medium-r-normal--10-100-75-75-c-80-iso10646-1","-lokaltog-fixed-medium-r-normal--10-100-75-75-c-60-iso8859-1" -g '1366x14' | (while read -r line; do ${line} > /dev/null 2>&1 ; done)
        ;;
    dzen2)
        PANEL_HEIGHT=24
        FONT_FAMILY='DejaVu Sans'
        FONT_SIZE=11
        cat "$PANEL_FIFO" | panel_dzen2 -f "$FONT_FAMILY" -s "$FONT_SIZE" | dzen2 -h $PANEL_HEIGHT -dock -ta l -title-name panel -fn "${FONT_FAMILY}:pixelsize=${FONT_SIZE}" -fg "$COLOR_FOREGROUND" -bg "$COLOR_BACKGROUND"
        ;;
esac
