#!/bin/bash

# Sleep until specified time
#
# Takes a 24hour time HH:MM as its argument
# Example:
# sleep_until 9:30
# sleep_until 18:45

# ------------------------------------------------------
# Argument check
if [ $# -lt 1 ]; then
    echo "Usage: sleep_until HH:MM"
fi

# Check whether specified time today or tomorrow
DESIRED=$((`date +%s -d "$1"`))
NOW=$((`date +%s`))
if [ $DESIRED -lt $NOW ]; then
	DESIRED=$((`date +%s -d "$1"` + 24*60*60))
fi

SECONDS=$(($DESIRED - $NOW))

# Set RTC wakeup time
sleep $SECONDS
